[package]
name = "zebra"
version = "0.5.0"
edition = "2021"

[dependencies]
prost = "0.11"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.9"
libyang = { path = "../../libyang" }
regex = "1.10"
similar = "2"
dirs = "5"

[build-dependencies]
tonic-build = "0.9"
